csv_gen_service/urls.py
"""
URL configuration for csv_gen_service project.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(
        "csv_generator.urls", namespace="csv_generator")
         ),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

csv_generator/urls.py
from django.urls import path, include

from csv_generator.views import (
    DataSchemaListView,
    DataSchemaCreateView,
    DataSchemaUpdateView,
    DataSchemaDeleteView,
    CSVGenerateView,
    CSVDownloadView,
)

app_name = "csv_generator"

urlpatterns = [
    path(
        "",
        DataSchemaListView.as_view(),
        name="schema-list"
    ),
    path(
        "schema/create/",
        DataSchemaCreateView.as_view(),
        name="schema-create"
    ),
    path(
        "schema/update/<int:pk>/",
        DataSchemaUpdateView.as_view(),
        name="schema-update"
    ),
    path(
        "schema/delete/<int:pk>/",
        DataSchemaDeleteView.as_view(),
        name="schema-delete"
    ),
    path(
        "schema/generate/<int:pk>/",
        CSVGenerateView.as_view(),
        name="csv-generate"
    ),
    path(
        "schema/generate/<int:pk>/download/",
        CSVDownloadView.as_view(),
        name="csv-download"
    ),
    path(
        "accounts/",
        include("django.contrib.auth.urls")
    ),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block title %}
    <title>Data Schemas</title>
  {% endblock %}
  <link rel="icon" href="{% static 'images/CSV_Generator_logo.svg' %}">
</head>
<body>
  {% block navbar %}
    {% include "includes/navbar.html" %}
  {% endblock %}
  <div class="base-div">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

templates/data_schema_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  <title>Delete Schema | CSV Generator</title>
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <h1 class="text-center">
          Delete Data Schema: {{ object.title }}?
        </h1>
      </div>
    </div>
    <div class="container m-3">
      <form action="" method="post">
      {% csrf_token %}
        <div class="row">
          <div class="col-md-3 mx-auto">
            <span>
              <input
                  class="btn btn-danger btn-lg custom-btn"
                  type="submit"
                  value="Yes"
              />
            </span>
            <span>
              <a
                  class="btn btn-success btn-lg custom-btn"
                  href="{% url 'csv_generator:schema-list' %}"
              >
                No
              </a>
            </span>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/data_schema_list.html
{% extends "base.html" %}

{% block title %}
    <title>Data Schemas | CSV Generator</title>
{% endblock %}

{% block content %}
  <div>
    <div class="container mb-3">
      <div class="row">
        <div class="col-sm-10">
           <h1>Data schemas</h1>
        </div>

        <div class="col-sm-2">
          <a
              type="button"
              class="btn btn-success btn-lg"
              href="{% url 'csv_generator:schema-create' %}"
          >
            New schema
          </a>

        </div>
      </div>
    </div>


    <div
        class="container-lg table-max"
    >
      {% if data_schemas %}
        <table
            class="table table-light table-hover table-striped"
        >
          <thead>
            <tr>
              <th scope="col" class="text-center">#</th>
              <th scope="col" class="text-center">Title</th>
              <th scope="col" class="text-center">Modified</th>
              <th scope="col" class="text-center">Actions</th>
            </tr>
          </thead>

          <tbody>
            {% for data_schema in data_schemas %}
              <tr>
                {% with forloop.counter0 as index %}
                  <th scope="row" class="text-center">{{ index|add:1 }}</th>
                  <td class="text-center">{{ data_schema.title }}</td>
                  <td class="text-center">{{ data_schema.modified }}</td>
                  <td class="text-center">
                     <a
                         class="link-primary custom-link"
                         href="{% url 'csv_generator:schema-update' pk=data_schema.id%}"
                     >
                       Edit
                     </a>
                     <a
                         class="link-danger custom-link"
                         href="{% url 'csv_generator:schema-delete' pk=data_schema.id%}"
                     >
                       Delete
                     </a>
                  </td>
                {% endwith %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
    {% else %}
      <h2>There are no data schemas</h2>
    {% endif%}
    </div>
  </div>
{% endblock %}

templates/generator_csv.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    <title>CSV Generator</title>
{% endblock %}
{% block content %}
  <div>
    <div id="data_schema_id" data-pk="{{ data_schema.pk }}"></div>
    <div class="container mb-3">
      <div class="row">
        <div class="col-sm-11">
            <h1>{{ data_schema.title }}</h1>
        </div>

        <div class="col-sm-1">
          <a
              type="button"
              class="btn btn-primary btn-lg"
              href="{% url 'csv_generator:schema-update'  pk=data_schema.id%}"
          >
            Edit
          </a>

        </div>
      </div>
    </div>


    <div
        class="container pdl-20"
    >
      {% if data_schema.schema_columns %}
        <table
            class="table table-light table-hover table-medium"
        >
          <thead>
            <tr>
              <th scope="col" class="text-center"># Order</th>
              <th scope="col" class="text-center">Column name</th>
              <th scope="col" class="text-center">Column type</th>
            </tr>
          </thead>

          <tbody>
            {% for column in data_schema.schema_columns.iterator %}
              <tr>
                <th scope="row" class="text-center">{{ column.order }}</th>
                <td class="text-center">{{ column.name }}</td>
                <td class="text-center">{{ column.type }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

      {% else %}
      <h2>There are no columns</h2>
    {% endif%}
    </div>

    <div class="container pd-20">
      <h2>Data Sets</h2>
      <p>
        You can create files as much as you would like to.
        <br>
        If you would like to have more than 500 rows - we can make it!
        <br>
        Please, wait until your CSV file will be created :)
      </p>
    </div>

    <div class="container pd-20">
      <form id="form">
        {% csrf_token %}

        <div>
          <div class="input-group mb-3">
            <span
                id="inputGroup-sizing-default"
                class="input-group-text"
            >
              Rows
            </span>
            <input
                id="row-input"
                type="number"
                name="rows"
                required
                disabled
            >
          </div>
          <div class="mb-3">
            <button
              type="submit"
              class="btn btn-success btn-lg"
          >
            Generate CSV
          </button>
          </div>
        </div>
        <p id="connection-info">Connection to the generate server...</p>
        </form>
    </div>

    <div
        class="container table-min"
    >
        <table
            class="table table-light table-hover"
        >
          <thead>
            <tr>
              <th scope="col" class="text-center">Order id</th>
              <th scope="col" class="text-center">Created</th>
              <th scope="col" class="text-center">Status</th>
              <th scope="col" class="text-center">Actions</th>
            </tr>
          </thead>

          <tbody id="csv-files">
            {% for csv_file in generated_csv_files.iterator %}
              <tr id="csv-file-{{ csv_file.id }}">
                <th scope="row" class="text-center">{{ csv_file.id }}</th>
                <td class="text-center">{{ csv_file.created|date:"Y-m-d" }}</td>
                <td class="text-center">
                  {% if csv_file.status == "Ready" %}
                    <div class="text-light bg-success rounded-3">
                    Ready
                    </div>
                  {% else %}
                    <div class="text-light bg-secondary rounded-3">
                    Processed
                    </div>
                  {% endif %}
                </td>
                <td class="text-center">
                  {% if csv_file.status == "Ready" %}
                    <a
                        href="{% url 'csv_generator:csv-download' csv_file.id %}"
                    >
                      Download
                    </a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
  </div>
  <script src="{% static 'js/web-socket.js' %}"></script>
{% endblock %}

templates/schema_form.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% crispy form %}

{% block title %}
    <title>{{ object|yesno:"Edit,Create" }} Schema | CSV Generator</title>
{% endblock %}

{% block content %}
  <div class="m-3">
    <form method="post">
      <div class=" mb-3">
        <div class="row">
          <div class="col-11">
             <h1>{{ object|yesno:"Edit,Create" }} schema</h1>
          </div>
          <div class="col-1">
            <button
                type="submit"
                class="btn btn-success btn-lg"
            >
              {{ object|yesno:"Edit,Create" }}
            </button>
          </div>
        </div>
      </div>

      {% csrf_token %}

      <div class="input-group mb-3 width-30">
        <span
            class="input-group-text"
            id="inputGroup-sizing-default"
        >
          Title
        </span>
        <input
            type="text"
            class="form-control"
            name="title"
            required
            value="{% if object %}{{ dataschema.title }}{% endif %}"
        >
        {% if form.errors.title %}
          {{ form.errors.title }}
        {% endif %}
      </div>

      <input type="hidden" name="user" required value="{{ user.id }}">

      <div class="row">
        <div>
          <h3>Schema Columns</h3>
        </div>
        <div>
          <hr>
          <p>
            You can add fields for a CSV file with different types following the rules:<br>
            <ul>
              <li>Column names, schema title and order should be unique;</li>
              <li>Column names and schema title should start with a letter and can consist of numbers and spaces;</li>
              <li>“From range” and “To range” fields are not required;</li>
              <li>You can choose the range of numbers for “Integer” type fields;</li>
              <li>You can choose the range of sentence count for “Text” type fields.</li>
           </ul>
           <b>Before creating click on “Delete” checkbox at fields which became unnecessary</b>
          </p>
          <br>
        </div>
      </div>
      <div
        class="container-lg table-medium"
      >
        <table
              class="table table-light table-hover"
        >
          <tbody id="children-form-table">
            {{ children.management_form }}
            {% if children %}
              {% for child in children %}
                <tr class="children-form">
                  {% for field in child %}
                    <td class="text-center">
                      {{ field|as_crispy_field }}
                    </td>
                  {% endfor %}
                </tr>
              {% endfor %}
            {% endif %}
            <tr id="empty-form" class="no-display">
              {% for field in children.empty_form %}
                <td class="text-center">
                  {{ field|as_crispy_field }}
                </td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>
      <button
          id="add-more"
          type="button"
          class="btn btn-secondary btn-lg mt-3"
      >
        Add column
      </button>
    </form>
    <br>
  </div>
  <script src="{% static 'js/add-column.js' %}"></script>
{% endblock %}